import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextVitals,
  ...nextTs,
  {
    // playwright-report/ and test-results/ are generated by `npm run
    // test:e2e` (Playwright's HTML report + trace viewer, which bundles its
    // own pre-minified vendor JS) — already gitignored, but eslint's flat
    // config doesn't read .gitignore automatically, so without this they
    // get linted as if they were our own source and produce a wall of
    // warnings (and even a couple of real-looking errors) from code we
    // don't own and that regenerates on every e2e run anyway.
    ignores: [".next/**", "node_modules/**", "next-env.d.ts", "scripts/**", "playwright-report/**", "test-results/**", "playwright/.cache/**"]
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", {
        varsIgnorePattern: "^_",
        argsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_"
      }]
    }
  }
];

export default eslintConfig;
